version 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2404:2024.01.2
        
    steps:
      - checkout
      - run: make deps
      - run: make test
workflows:
  basic:
    jobs:
      - build-and-test
- run: make docker_build 